name: paynest-db

services:
  paynest-migrations:
    build: .
    container_name: paynest-migrations
    restart: "no"
    volumes:
      - pocketbase-data:/app/pb_data

  pocketbase:
    image: ghcr.io/coollabsio/pocketbase:latest
    container_name: paynest-pocketbase
    environment:
      - SERVICE_URL_POCKETBASE_8080
    depends_on:
      paynest-migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "${POCKETBASE_PORT:-8090}:8080"
    volumes:
      - pocketbase-data:/app/pb_data
      - pocketbase-hooks:/app/pb_hooks
    command:
      - serve
      - --http=0.0.0.0:8080
      - --dir=/app/pb_data

volumes:
  pocketbase-data:
  pocketbase-hooks:
