/// <reference path="../pb_data/types.d.ts" />

migrate((app) => {
  const subscriptions = new Collection({
    id: "pbc_paynestsub",
    listRule: "user = @request.auth.id",
    viewRule: "user = @request.auth.id",
    createRule: "user = @request.auth.id",
    updateRule: "user = @request.auth.id",
    deleteRule: "user = @request.auth.id",
    name: "subscriptions",
    type: "base",
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        hidden: false,
        id: "autodate2990389176",
        name: "created",
        onCreate: true,
        onUpdate: false,
        presentable: false,
        system: true,
        type: "autodate",
      },
      {
        hidden: false,
        id: "autodate3332085495",
        name: "updated",
        onCreate: true,
        onUpdate: true,
        presentable: false,
        system: true,
        type: "autodate",
      },
      {
        cascadeDelete: true,
        collectionId: "_pb_users_auth_",
        hidden: false,
        id: "relation_paynest_user",
        maxSelect: 1,
        minSelect: 0,
        name: "user",
        presentable: false,
        required: true,
        system: false,
        type: "relation",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_name",
        max: 0,
        min: 0,
        name: "name",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_category",
        max: 0,
        min: 0,
        name: "category",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "number_subscription_price",
        max: null,
        min: 0,
        name: "price",
        onlyInt: false,
        presentable: false,
        required: true,
        system: false,
        type: "number",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_currency",
        max: 0,
        min: 0,
        name: "currency",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select_subscription_period",
        maxSelect: 1,
        name: "billing_period",
        presentable: false,
        required: true,
        system: false,
        type: "select",
        values: ["Weekly", "Monthly", "3 months", "6 months", "Yearly"],
      },
      {
        hidden: false,
        id: "number_subscription_pay_day",
        max: 31,
        min: 1,
        name: "pay_day",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "date_subscription_next_renewal",
        max: "",
        min: "",
        name: "next_renewal_date",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "bool_subscription_paused",
        name: "paused",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "bool_subscription_reminder_enabled",
        name: "reminder_enabled",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "number_subscription_reminder_days",
        max: null,
        min: 0,
        name: "reminder_days",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_reminder_time",
        max: 0,
        min: 0,
        name: "reminder_time",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_icon_name",
        max: 0,
        min: 0,
        name: "icon_name",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_icon_label",
        max: 0,
        min: 0,
        name: "icon_label",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_icon_color",
        max: 0,
        min: 0,
        name: "icon_color",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_background_color",
        max: 0,
        min: 0,
        name: "background_color",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_icon_bg_color",
        max: 0,
        min: 0,
        name: "icon_background_color",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_simple_icon_slug",
        max: 0,
        min: 0,
        name: "simple_icon_slug",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_icon_provider",
        max: 0,
        min: 0,
        name: "icon_provider",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        exceptDomains: null,
        hidden: false,
        id: "url_subscription_icon_url",
        name: "icon_url",
        onlyDomains: null,
        presentable: false,
        required: false,
        system: false,
        type: "url",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_icon_source_title",
        max: 0,
        min: 0,
        name: "icon_source_title",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_created_at",
        max: 0,
        min: 0,
        name: "created_at",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_subscription_updated_at",
        max: 0,
        min: 0,
        name: "updated_at",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
    ],
    indexes: [],
    system: false,
  });

  const settings = new Collection({
    id: "pbc_paynestset",
    listRule: "user = @request.auth.id",
    viewRule: "user = @request.auth.id",
    createRule: "user = @request.auth.id",
    updateRule: "user = @request.auth.id",
    deleteRule: "user = @request.auth.id",
    name: "settings",
    type: "base",
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        hidden: false,
        id: "autodate2990389176",
        name: "created",
        onCreate: true,
        onUpdate: false,
        presentable: false,
        system: true,
        type: "autodate",
      },
      {
        hidden: false,
        id: "autodate3332085495",
        name: "updated",
        onCreate: true,
        onUpdate: true,
        presentable: false,
        system: true,
        type: "autodate",
      },
      {
        cascadeDelete: true,
        collectionId: "_pb_users_auth_",
        hidden: false,
        id: "relation_paynest_settings_user",
        maxSelect: 1,
        minSelect: 0,
        name: "user",
        presentable: false,
        required: true,
        system: false,
        type: "relation",
      },
      {
        hidden: false,
        id: "bool_settings_reminders_enabled",
        name: "reminders_enabled",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "number_settings_reminder_days",
        max: null,
        min: 0,
        name: "reminder_days",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_settings_currency",
        max: 0,
        min: 0,
        name: "currency",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "bool_settings_payday_enabled",
        name: "payday_enabled",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "number_settings_payday",
        max: 31,
        min: 1,
        name: "payday",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_settings_color_presets",
        max: 0,
        min: 0,
        name: "color_presets",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_settings_updated_at",
        max: 0,
        min: 0,
        name: "updated_at",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
    ],
    indexes: ["CREATE UNIQUE INDEX `idx_settings_user` ON `settings` (`user`)"],
    system: false,
  });

  app.save(subscriptions);
  app.save(settings);
}, (app) => {
  const settings = app.findCollectionByNameOrId("pbc_paynestset");
  app.delete(settings);

  const subscriptions = app.findCollectionByNameOrId("pbc_paynestsub");
  app.delete(subscriptions);
});
